deployment:
  tasks:
    - export NODE_ENV=production
    - cd /home/ryangvdo/RyanPalmResume/my-resume-site
    - /opt/cpanel/ea-nodejs18/bin/npm install
    - /opt/cpanel/ea-nodejs18/bin/npm run build
    - rm -rf /home/ryangvdo/public_html/*
    - cp -r /home/ryangvdo/RyanPalmResume/my-resume-site/dist/* /home/ryangvdo/public_html/